version: "3"
services:
  python:
      build: .
      working_dir: /app
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
      volumes: 
      -  ./:/app
      tty: true